version: 3.2
service:
  mpsetup:
    image: nginx:latest 
    name: mpsetup
    port: 8080
    ContainerPath: /tmp
    ServiceLocalPath: /tmp
    ReplicaSet: 2
    configmaps:
      APP_DEBUG: "true"
      APP_ENV: local
      APP_KEY: base64:1Ykb1MNf9qwdUIUpElWUxReKWr+4iL106Z43SuyqSr0=
    tags: 
      - core
  mpms1:
    image: mpms1:latest 
    name: mpms1 
    port: 8080
    ContainerPath: /tmp
    ServiceLocalPath: /tmp
    ReplicaSet: 3
    configmaps:
      APP_DEBUG: "true"
      APP_ENV: local
      APP_KEY: base64:1Ykb1MNf9qwdUIUpElWUxReKWr+4iL106Z43SuyqSr0=
    tags: 
      - dev
